<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Frent" Version="0.8.0-beta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Discord.ID.Data\src\Discord.ID.Data.csproj" />
    <ProjectReference Include="..\..\Status.Data\src\Status.Data.csproj" />
  </ItemGroup>

</Project>
